dashboard:
  currency: RUB
  electricity_price: 5.0
  fuel_price: 50.0
  language: ru
  maps:
    api_key: ''
    provider: openstreetmap
  theme: auto
  timezone: Europe/Moscow
  units: metric
data:
  cache_enabled: true
  cache_ttl: 300
experimental:
  ai_trip_analysis: false
  eco_coaching: false
  predictive_maintenance: false
  route_optimization: false
logging:
  backup_count: 5
  file_path: logs/toyota-dashboard.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: ERROR
  max_file_size: 10MB
monitoring:
  auto_refresh: true
  data_collection_interval: 300
  max_api_calls_per_hour: 100
  trip_detection: true
notifications:
  daily_reports: true
  low_battery_threshold: 20
  low_fuel_threshold: 50
  maintenance_alerts: true
  trip_summaries: true
  weekly_reports: true
performance:
  cache_enabled: true
  cache_ttl: 300
  max_concurrent_requests: 10
  request_timeout: 30
phev_settings:
  charge_threshold_alert: 80
  charging_schedule: '22:00'
  ev_mode_preference: true
  preconditioning_enabled: true
  target_charge_level: 80
security:
  allowed_ips: []
  enable_https: false
  session_timeout: 3600
  ssl_cert_path: ''
  ssl_key_path: ''
server:
  debug: false
  host: 0.0.0.0
  port: 12000
  secret_key: your-secret-key-here
toyota:
  password: $@nfiSK3
  region: europe
  username: sanfisko@gmail.com
  vin: JTPABACA90R004975
